import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

// Generates an inspectable inventory from the committed Windows dependency graph.
// License-file omissions are listed explicitly; this does not certify compliance.
const projectRoot = process.cwd();
const metadata = JSON.parse(execFileSync("cargo", [
  "metadata", "--locked", "--format-version", "1",
  "--filter-platform", "x86_64-pc-windows-msvc",
  "--manifest-path", "src-tauri/Cargo.toml",
], { encoding: "utf8", maxBuffer: 20 * 1024 * 1024 }));
const lock = JSON.parse(fs.readFileSync("package-lock.json", "utf8"));
const resolved = new Set(metadata.resolve.nodes.map((node) => node.id));
const notices = new Map();
const missing = [];
const verifiedUpstreamNotices = JSON.parse(fs.readFileSync(".github/licenses/verified-upstream-notices.json", "utf8"));
const recoveredNotices = [];

function markdownCell(value) {
  return String(value ?? "Unknown").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function licenseFiles(directory, extraFile) {
  const files = [];
  function collect(location, depth = 0) {
    if (!fs.existsSync(location)) return;
    if (fs.statSync(location).isFile()) {
      files.push(location);
    } else if (depth < 2) {
      for (const name of fs.readdirSync(location).sort()) collect(path.join(location, name), depth + 1);
    }
  }
  for (const name of fs.readdirSync(directory).sort()) {
    if (/^(licen[cs]e|copying|notice|copyright|unlicense)([._-]|$)/i.test(name)) {
      collect(path.join(directory, name));
    }
  }
  if (extraFile) collect(path.resolve(directory, extraFile));
  return [...new Set(files)];
}

function registerNotice(dependency, sourceText) {
  const text = sourceText.replaceAll("\r\n", "\n").trim();
  const digest = createHash("sha256").update(text).digest("hex");
  const existing = notices.get(digest);
  if (existing) existing.dependencies.add(dependency);
  else notices.set(digest, { text, dependencies: new Set([dependency]) });
}

function attachNotices(dependency, files, crate) {
  if (!files.length && crate) {
    const vcsFile = path.join(path.dirname(crate.manifest_path), ".cargo_vcs_info.json");
    const vcs = fs.existsSync(vcsFile) ? JSON.parse(fs.readFileSync(vcsFile, "utf8")) : null;
    const recovered = verifiedUpstreamNotices.find((record) => record.name === crate.name && record.version === crate.version && record.repository === crate.repository && record.commit === vcs?.git?.sha1);
    if (recovered) {
      for (const notice of recovered.notices) {
        if (createHash("sha256").update(notice.text).digest("hex") !== notice.sha256) {
          throw new Error(`Cached upstream notice checksum mismatch for ${dependency}`);
        }
        registerNotice(dependency, notice.text);
      }
      recoveredNotices.push(recovered);
      return;
    }
  }
  if (!files.length) missing.push(dependency);
  for (const file of files) registerNotice(dependency, fs.readFileSync(file, "utf8"));
}

const lines = [
  "# Third-party notices", "",
  "Generated by `node .github/scripts/generate-notices.mjs` from the committed lockfiles and the Windows dependency graph. Regenerate after dependency changes using a locked installation (`npm ci`). This inventory intentionally includes Rust build dependencies as well as runtime dependencies; not every listed crate is shipped in the final executable.", "",
  "Vellora was originally built as OpenFlow. The project's original attribution identifies OpenWhispr (https://github.com/OpenWhispr/openwhispr) and FreeFlow (https://github.com/zachlatta/freeflow) as product/workflow references. The owner reports development solely with AI agents. The current logo was generated through Codex's built-in OpenAI image generation tool on October 4, 2026; its text prompts, image inputs and asset hashes are recorded in docs/ARTWORK_PROVENANCE.md. Earlier unverified artwork remains only in private historical material; see docs/LICENSING_REVIEW.md for the clean-history publication plan and rights limitations.", "",
  "Upstream license declarations and available license/notice texts are reproduced below. Vellora's MIT license does not replace any dependency's license. For MPL-2.0 components, upstream source is available from the crate source links in the inventory. A public binary release requires a final license review, including any listed gaps. This file, Vellora's LICENSE and THIRD_PARTY_NOTICES_NATIVE.md are included as installer resources; the supplemental file covers external Windows installer/loader components outside the Cargo/npm inventory.", "",
  "## JavaScript runtime dependencies", "",
  "| Package | Version | License | Source |",
  "| --- | --- | --- | --- |",
];

for (const [location, dependency] of Object.entries(lock.packages).filter(([location, dependency]) => location && !dependency.dev).sort(([a], [b]) => a.localeCompare(b))) {
  const packageDirectory = path.join(projectRoot, location);
  const packageJson = JSON.parse(fs.readFileSync(path.join(packageDirectory, "package.json"), "utf8"));
  const name = packageJson.name;
  lines.push(`| ${markdownCell(name)} | ${markdownCell(dependency.version)} | ${markdownCell(dependency.license ?? packageJson.license)} | [npm](https://www.npmjs.com/package/${encodeURIComponent(name)}/v/${dependency.version}) |`);
  attachNotices(`${name} ${dependency.version}`, licenseFiles(packageDirectory));
}

lines.push("", "## Rust Windows dependency inventory", "", "| Crate | Version | License declaration | Upstream source |", "| --- | --- | --- | --- |");
for (const crate of metadata.packages.filter((crate) => crate.source && resolved.has(crate.id)).sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))) {
  lines.push(`| ${markdownCell(crate.name)} | ${markdownCell(crate.version)} | ${markdownCell(crate.license)} | [crate](https://crates.io/crates/${crate.name}/${crate.version}) / [source](https://docs.rs/crate/${crate.name}/${crate.version}/source/) |`);
  attachNotices(`${crate.name} ${crate.version}`, licenseFiles(path.dirname(crate.manifest_path), crate.license_file), crate);
}

lines.push("", "## Verified upstream notices recovered from exact source commits", "", "Some crate packages omit their workspace license files. Their published `.cargo_vcs_info.json` identifies the exact source commit used below. Dual-licensed MIT/Apache packages use the MIT option in these recovered notices. For `selectors`, the MPL-2.0 header is preserved from the exact upstream source file and the license text comes from Mozilla, its license steward.", "");
for (const record of recoveredNotices) {
  lines.push(`- ${record.name} ${record.version}, commit \`${record.commit}\`: ${record.notices.map((notice) => `[notice source](${notice.source})`).join(", ")}.`);
}

lines.push("", missing.length ? "## Missing upstream notice files — public binary release blocker" : "## Notice coverage", "");
if (missing.length) {
  lines.push("The downloaded packages below declare a license but do not include a recognized top-level license or notice file. Verify their upstream copyright and license texts before public binary distribution. This is not an obstacle to publishing Vellora's own source under MIT.", "");
  for (const dependency of missing) lines.push(`- ${dependency}`);
} else {
  lines.push("Every listed package has an included license or notice text, either from its published archive or the verified upstream sources above. This verifies notice-file coverage, not every possible distribution obligation; a final distribution license review is still required.");
}

lines.push("", "## Upstream license and notice texts", "");
let index = 0;
for (const notice of notices.values()) {
  index += 1;
  lines.push(`### Notice ${index}`, "", `Applies to: ${[...notice.dependencies].join(", ")}.`, "", "````text", notice.text, "````", "");
}
fs.writeFileSync("THIRD_PARTY_NOTICES.md", `${lines.map((line) => line.replace(/[ \t]+$/gm, "")).join("\n").trimEnd()}\n`);
console.log(`Generated ${index} distinct notice texts; ${missing.length} packages need upstream notice verification.`);
